[project]
name = "festival-scraper"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Maximilian Prusch", email = "maximilian.prusch@outlook.com" }
]
dependencies = [
    "requests>=2.31.0",
    "boto3>=1.34.60",
    "beautifulsoup4>=4.12.3",
    "pip>=24.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.1.1",
    "responses>=0.25.0",
    "boto3-stubs[ssm,s3]>=1.34.60",
    "moto[ssm,s3]>=5.0.3",
    "ruff>=0.3.3",
    "pip>=24.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/festival_scraper"]
