version: '3'

tasks:
  install:
    desc: Install all dependencies
    cmds: [ rye sync ]
  format:
    cmds:
    - rye lint
    - rye fmt
  test:
    desc: Run all tests
    cmds: [ rye run pytest ]
  build:
    desc: Build and zip everything for a lambda deployment
    cmds:
      - rm -rf dist
      - pip install --target ./dist -r requirements.lock
      - task: zip
      - zip -r dist/festival-scraper.zip src
      - zip -r dist/festival-scraper.zip handler.py
  zip:
    dir: dist
    cmds:
      - zip -r festival-scraper.zip .

  ci:
    deps: [ install ]
    cmds:
    - task: format
    - task: test

  deploy:
    deps: [ build ]
    dir: aws
    cmds:
    - aws cloudformation deploy --template-file cloudformation.yml --stack-name WackenArtists --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides
      ParamFestivalBucketArn=/festival-bucket/arn
      ParamFestivalBucketName=/festival-bucket/name
      ParamDeploymentBucketName=/music-rating/deployment-bucket/name
      ParamFunctionVersion={{.WACKEN_VERSION_ID}}
      --profile music-rating
    vars:
      WACKEN_VERSION_ID:
        sh: aws s3api put-object --bucket music-rating-deployment-bucket --key festival-scraper.zip --body ../dist/festival-scraper.zip --profile music-rating | jq -r .VersionId

