version: '3'

tasks:
  default:
    cmds:
    - task: format
    - task: test
  install:
    desc: Install all dependencies
    cmds: [ uv sync --all-extras --dev ]
  format:
    cmds:
    - uv run ruff format
    - uv run ruff check --fix
  test:
    desc: Run all tests
    cmds: [ uv run pytest ]
  build:
    desc: Build and zip everything for a lambda deployment
    cmds:
      - rm -rf dist
      - uv pip install --target ./dist -r pyproject.toml
      - task: zip
      - zip -r dist/festival-scraper.zip src
      - zip -r dist/festival-scraper.zip handler.py
  zip:
    dir: dist
    cmds:
      - zip -q -r festival-scraper.zip .

  ci:
    deps: [ install ]
    cmds:
    - task: format
    - task: test

  deploy:
    deps: [ build ]
    dir: aws
    cmds: [ task: deploy-to-aws ]
  deploy-to-aws:
    dir: aws
    cmds:
    - aws cloudformation deploy --template-file cloudformation.yml --stack-name FestivalScraper --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides
      ParamFestivalBucketArn=/festival-bucket/arn
      ParamFestivalBucketName=/festival-bucket/name
      ParamDeploymentBucketName=/music-rating/deployment-bucket/name
      ParamFunctionVersion={{.WACKEN_VERSION_ID}}
      --profile music-rating
    vars:
      WACKEN_VERSION_ID:
        sh: aws s3api put-object --bucket music-rating-deployment-bucket --key festival-scraper.zip --body ../dist/festival-scraper.zip --profile music-rating | jq -r .VersionId

