name: Test and Deploy
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoout
        uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Test
        run: |
          task ci
        env:
          UV_SYSTEM_PYTHON: 1
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Deploy Lambda
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile music-rating
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile music-rating
          task deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_DEPLOY_ACCESS_KEY_SECRET }}
          AWS_DEFAULT_REGION: eu-west-1
          UV_SYSTEM_PYTHON: 1
