name: Test-PR
on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Test
      run: |
        task ci
            env:
        UV_SYSTEM_PYTHON: 1
